services:
  - type: private_service
    name: mysql-db
    env: docker
    plan: starter
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    disk:
      name: mysql-data
      mountPath: /var/lib/mysql
      sizeGB: 10
    envVars:
      - key: MYSQL_ROOT_PASSWORD
      - key: MYSQL_DATABASE
      - key: MYSQL_USER
      - key: MYSQL_PASSWORD
